export const strings = {
    addForm: 'add-form'
};

export const selectors = {
    table: 'table.watched-automated-processes',
    addForm: '#add-form',
    clientSelect: 'select#client',
    nameInput: 'input#name',
    codeInput: 'input#code',
    operationalHandbookPageURLInput: 'input#operational_handbook_page_url',
    kibanaDashboardURLInput: 'input#kibana_dashboard_url',
    additionalInformationTextarea: 'textarea#additional_information',
    runningPeriodSection: 'div.running-period-section',
    runningPeriodSectionTitle: 'div.running-period-section .subtitle-level h1',
    runningPeriodSectionTitleIcon: 'div.running-period-section .subtitle-level span.icon',
    runningPeriodCalendar: 'input#running_period_times',
    runningPeriodMondayCheckbox: 'input#running_period_monday',
    runningPeriodTuesdayCheckbox: 'input#running_period_tuesday',
    runningPeriodWednesdayCheckbox: 'input#running_period_wednesday',
    runningPeriodThursdayCheckbox: 'input#running_period_thursday',
    runningPeriodFridayCheckbox: 'input#running_period_friday',
    runningPeriodSaturdayCheckbox: 'input#running_period_saturday',
    runningPeriodSundayCheckbox: 'input#running_period_sunday',
    involvedProcessesSection: 'div.involved-processes-section',
    involvedProcessesSectionTitle: 'div.involved-processes-section .subtitle-level h1',
    involvedProcessesSectionTitleIcon: 'div.involved-processes-section .subtitle-level span.icon',
    involvedProcessesCount: 'div.involved-processes-section span.tag',
    involvedProcessesTable: 'table.involved-processes-table',
    involvedRobotsSection: 'div.involved-robots-section',
    involvedRobotsSectionTitle: 'div.involved-robots-section .subtitle-level h1',
    involvedRobotsSectionTitleIcon: 'div.involved-robots-section .subtitle-level span.icon',
    involvedRobotsCount: 'div.involved-robots-section span.tag',
    involvedRobotsTable: 'table.involved-robots-table',
    involvedQueuesSection: 'div.involved-queues-section',
    involvedQueuesSectionTitle: 'div.involved-queues-section .subtitle-level h1',
    involvedQueuesSectionTitleIcon: 'div.involved-queues-section .subtitle-level span.icon',
    involvedQueuesCount: 'div.involved-queues-section span.tag',
    involvedQueuesTable: 'table.involved-queues-table',
    createButton: 'button.create',
    createButtonChildren: 'button.create *',
    resetButton: 'button.reset',
    resetButtonChildren: 'button.reset *'
};

export const elements = {
    table: document.querySelector(selectors.table),
    addForm: document.querySelector(selectors.addForm),
    runningPeriodSection: document.querySelector(selectors.runningPeriodSection),
    runningPeriodSectionTitle: document.querySelector(selectors.runningPeriodSectionTitle),
    runningPeriodSectionTitleIcon: document.querySelector(selectors.runningPeriodSectionTitleIcon),
    involvedProcessesSection: document.querySelector(selectors.involvedProcessesSection),
    involvedProcessesSectionTitle: document.querySelector(selectors.involvedProcessesSectionTitle),
    involvedProcessesSectionTitleIcon: document.querySelector(selectors.involvedProcessesSectionTitleIcon),
    involvedProcessesCount: document.querySelector(selectors.involvedProcessesCount),
    involvedRobotsSection: document.querySelector(selectors.involvedRobotsSection),
    involvedRobotsSectionTitle: document.querySelector(selectors.involvedRobotsSectionTitle),
    involvedRobotsSectionTitleIcon: document.querySelector(selectors.involvedRobotsSectionTitleIcon),
    involvedRobotsCount: document.querySelector(selectors.involvedRobotsCount),
    involvedQueuesSection: document.querySelector(selectors.involvedQueuesSection),
    involvedQueuesSectionTitle: document.querySelector(selectors.involvedQueuesSectionTitle),
    involvedQueuesSectionTitleIcon: document.querySelector(selectors.involvedQueuesSectionTitleIcon),
    involvedQueuesCount: document.querySelector(selectors.involvedQueuesCount),
    createButton: document.querySelector(selectors.createButton),
    resetButton: document.querySelector(selectors.resetButton)
};