export const strings = {
    addForm: 'add-form'
};

export const selectors = {
    table: 'table.watched-automated-processes',
    formsSection: '.forms-section',
    addFormSection: '.add-form-section',
    addForm: '#add-form',
    editFormSection: '.edit-form-section',
    editForm: '#edit-form',
    clientSelect: 'select.client',
    nameInput: 'input.name',
    codeInput: 'input.code',
    operationalHandbookPageURLInput: 'input.operational_handbook_page_url',
    kibanaDashboardURLInput: 'input.kibana_dashboard_url',
    additionalInformationTextarea: 'textarea.additional_information',
    runningPeriodSection: 'div.running-period-section',
    runningPeriodSectionTitle: 'div.running-period-section .subtitle-level h1',
    runningPeriodSectionTitleIcon: 'div.running-period-section .subtitle-level span.icon',
    runningPeriodCalendar: 'input.running_period_times',
    runningPeriodMondayCheckbox: 'input.running_period_monday',
    runningPeriodTuesdayCheckbox: 'input.running_period_tuesday',
    runningPeriodWednesdayCheckbox: 'input.running_period_wednesday',
    runningPeriodThursdayCheckbox: 'input.running_period_thursday',
    runningPeriodFridayCheckbox: 'input.running_period_friday',
    runningPeriodSaturdayCheckbox: 'input.running_period_saturday',
    runningPeriodSundayCheckbox: 'input.running_period_sunday',
    involvedProcessesSection: 'div.involved-processes-section',
    involvedProcessesSectionTitle: 'div.involved-processes-section .subtitle-level h1',
    involvedProcessesSectionTitleIcon: 'div.involved-processes-section .subtitle-level span.icon',
    involvedProcessesCount: 'div.involved-processes-section span.tag',
    involvedProcessesTable: 'table.involved-processes-table',
    involvedRobotsSection: 'div.involved-robots-section',
    involvedRobotsSectionTitle: 'div.involved-robots-section .subtitle-level h1',
    involvedRobotsSectionTitleIcon: 'div.involved-robots-section .subtitle-level span.icon',
    involvedRobotsCount: 'div.involved-robots-section span.tag',
    involvedRobotsTable: 'table.involved-robots-table',
    involvedQueuesSection: 'div.involved-queues-section',
    involvedQueuesSectionTitle: 'div.involved-queues-section .subtitle-level h1',
    involvedQueuesSectionTitleIcon: 'div.involved-queues-section .subtitle-level span.icon',
    involvedQueuesCount: 'div.involved-queues-section span.tag',
    involvedQueuesTable: 'table.involved-queues-table',
    createButton: 'button.create',
    createButtonChildren: 'button.create *',
    resetButton: 'button.reset',
    resetButtonChildren: 'button.reset *',
    saveButton: 'button.save',
    saveButtonChildren: 'button.save *',
    cancelButton: 'button.cancel',
    cancelButtonChildren: 'button.cancel *',
    removeButton: 'button.remove',
    removeButtonChildren: 'button.remove *'
};

export const elements = {
    table: document.querySelector(selectors.table),
    formsSection: document.querySelector(selectors.formsSection),
    addForm: document.querySelector(selectors.addForm)
};